### ISSUE TITLE
"llm.nvim has timed out!"

### ISSUE THREAD

**Issue by curiousgeorgios** [melbaldove/llm.nvim#10]
Keep getting llm.nvim has timed out! Happens with both Groq and OpenAI - Groq works intermittently but when it does work it only completes a few LOC before timing out again...

What am I doing wrong? Have tried to increase timeout with no luck either.

![image](https://github.com/melbaldove/llm.nvim/assets/101997181/5d544d9b-fab8-4989-845c-e412cd94c49d)

**Comment by melbaldove** [comment]
related to #5 

im guessing you are on linux aswell? sorry im unable to debug this at the moment as im on a mac. can you try this [PR](https://github.com/melbaldove/llm.nvim/pull/8) if it fixes your issue? the author replaced nio with plenary

**Comment by melbaldove** [comment]
related to #5 

im guessing you are on linux aswell? sorry im unable to debug this at the moment as im on a mac. can you try this [PR](https://github.com/melbaldove/llm.nvim/pull/8)  if it fixes your issue? the author replaced nio with plenary

**Comment by fastdaima** [comment]
facing the same issue in ubuntu 20.04. 

If its possible can you add some steps to add llm.nvim to init.nvim, such that I will also verify it from my end.

**Comment by curiousgeorgios** [comment]
> related to #5
> 
> im guessing you are on linux aswell? sorry im unable to debug this at the moment as im on a mac. can you try this [PR](https://github.com/melbaldove/llm.nvim/pull/8) if it fixes your issue? the author replaced nio with plenary

Ahhhh thanks for that - I didn't read the full thread on #5 - works by using the commit replacing nio with plenary! (and yes i'm on Linux) 

Here's the part of the config for anyone else having this issue:

```lua
return {
  {
    "melbaldove/llm.nvim",
    dependencies = { "nvim-neotest/nvim-nio" },
    commit = "09bdfad4a76dff82ced2a10095552eba4885d6bd",
    }
}
```
