### ISSUE TITLE
Custom system prompt?

### ISSUE THREAD

**Issue by pixqc** [melbaldove/llm.nvim#7]
Hi, thanks for making this small Neovim plugin. It'd be great if I can customize the system prompt directly from `init.lua`. I'm going to fork and play around with it, and I'll make a PR if I get a thumbs up :)

**Comment by pixqc** [comment]
Okay, it works now!

<img width="701" alt="image" src="https://github.com/melbaldove/llm.nvim/assets/170739895/d2b27800-6c91-40eb-9369-3c46d46b2a98">

<img width="612" alt="image" src="https://github.com/melbaldove/llm.nvim/assets/170739895/25e5f203-de25-4ad9-aa80-c0dc7add6f14">

Commit: https://github.com/pixqc/llm.nvim/commit/d93fda92230b569f6f2484ee886f44a4bd0818ef

**Comment by melbaldove** [comment]
nice please PR!
